import pytest

from laboratories import Manifold


@pytest.fixture
def manifold() -> Manifold:
    grid_string = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """
    return Manifold(grid_string)


def test_manifold():
    grid_string = ".S.\n.^.\n"
    manifold = Manifold(grid_string)
    assert manifold.grid == [[".", "S", "."], [".", "^", "."]]
    assert manifold.start == 1


def test_count_splits(manifold: Manifold):
    assert manifold.count_splits() == 21


def test_count_timelines(manifold: Manifold):
    assert manifold.count_timelines() == 40
